/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petadoptiontracker.view;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import petadoptiontracker.dao.UserDao;
import petadoptiontracker.model.UserData;

/**
 *
 * @author keshab
 */
public class AdminDashboardView extends javax.swing.JFrame {
     public AdminDashboardView(UserData user) {
        initComponents();
        
        jLabel1.setText("Welcome, " + user.getName() +" "+user.getRole()+ "!");
        
        byte[] imageData = user.getImage();
        if (imageData != null) {
            ImageIcon imageIcon = new ImageIcon(imageData);
            // Resize image to fit label size (optional)
            Image img = imageIcon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(img);
            photoLabel.setIcon(imageIcon);
        }
    }
    /**
     * Creates new form DashboardView
     */
    public AdminDashboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        addPetTab = new javax.swing.JButton();
        dashboardButton = new javax.swing.JButton();
        viewPetTab = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameResult = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailResult = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        petStatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        petBreed1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        petAge1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        petPhotoUploadButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        petName2 = new javax.swing.JTextField();
        addPetButton = new javax.swing.JButton();
        petSex1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 535));
        setSize(new java.awt.Dimension(950, 535));
        getContentPane().setLayout(null);

        jLabel1.setText("Dashboard");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 10, 170, 20);

        photoLabel.setText("jLabel2");
        photoLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        photoLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        getContentPane().add(photoLabel);
        photoLabel.setBounds(68, 34, 80, 80);

<<<<<<< HEAD
        myRequestButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        myRequestButton.setText("My Request");
        getContentPane().add(myRequestButton);
        myRequestButton.setBounds(34, 187, 152, 31);
=======
        addPetTab.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addPetTab.setText("My Request");
        getContentPane().add(addPetTab);
        addPetTab.setBounds(34, 187, 152, 31);
>>>>>>> 47cae230d9c98be4f28adda223dd639c4f2bc686

        dashboardButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        dashboardButton.setText("Dashboard");
        getContentPane().add(dashboardButton);
        dashboardButton.setBounds(34, 126, 152, 31);

<<<<<<< HEAD
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton4.setText("Profile Setting");
        getContentPane().add(jButton4);
        jButton4.setBounds(34, 243, 157, 31);
=======
        viewPetTab.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        viewPetTab.setText("Profile Setting");
        getContentPane().add(viewPetTab);
        viewPetTab.setBounds(34, 243, 157, 31);
>>>>>>> 47cae230d9c98be4f28adda223dd639c4f2bc686

        signOutButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        signOutButton.setText("Sign Out");
        getContentPane().add(signOutButton);
        signOutButton.setBounds(34, 303, 152, 31);

        jLabel2.setText("This is Admin Dashboard");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 40, 170, 20);
        getContentPane().add(searchField);
        searchField.setBounds(320, 60, 195, 22);

        searchButton.setText("Search");
        getContentPane().add(searchButton);
        searchButton.setBounds(520, 60, 72, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(371, 303, 0, 0);

        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 450, 32, 16);
        getContentPane().add(nameResult);
        nameResult.setBounds(340, 450, 130, 22);

        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 450, 30, 16);
        getContentPane().add(emailResult);
        emailResult.setBounds(540, 450, 189, 22);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 270, 510);

        jPanel4.setLayout(null);

        jLabel10.setText("This is tab 2");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(170, 70, 100, 60);

        jTabbedPane4.addTab("tab2", jPanel4);

        jPanel5.setLayout(null);

        jLabel11.setText("This is tab 3");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(210, 40, 110, 40);

        jTabbedPane4.addTab("tab3", jPanel5);

        jPanel3.setLayout(null);

        petStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Availabe", "Not Available" }));
        petStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petStatusActionPerformed(evt);
            }
        });
        jPanel3.add(petStatus);
        petStatus.setBounds(260, 90, 120, 20);

        jLabel9.setText("Add Pet");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(130, 20, 68, 16);

        jLabel6.setText("Status");
        jPanel3.add(jLabel6);
<<<<<<< HEAD
        jLabel6.setBounds(280, 60, 90, 20);
        jPanel3.add(petSex);
        petSex.setBounds(150, 170, 64, 22);
=======
        jLabel6.setBounds(260, 60, 90, 20);
>>>>>>> 47cae230d9c98be4f28adda223dd639c4f2bc686

        jLabel7.setText("Category (cat/dog)");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 70, 120, 20);
<<<<<<< HEAD
        jPanel3.add(petStatus);
        petStatus.setBounds(270, 90, 64, 22);
=======
>>>>>>> 47cae230d9c98be4f28adda223dd639c4f2bc686

        jLabel8.setText("Breed");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 110, 90, 20);
        jPanel3.add(petBreed1);
        petBreed1.setBounds(150, 110, 64, 22);

        jLabel12.setText("Age");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 140, 90, 20);
        jPanel3.add(petAge1);
        petAge1.setBounds(150, 140, 64, 22);

        jLabel13.setText("Sex");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 170, 90, 20);

        petPhotoUploadButton.setText("Upload");
        jPanel3.add(petPhotoUploadButton);
        petPhotoUploadButton.setBounds(150, 210, 72, 23);

        jLabel14.setText("Pet Photo");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(30, 210, 90, 20);
        jPanel3.add(petName2);
        petName2.setBounds(150, 70, 64, 22);

        addPetButton.setText("Add Pet");
        jPanel3.add(addPetButton);
        addPetButton.setBounds(280, 160, 72, 23);
<<<<<<< HEAD
=======

        petSex1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        petSex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petSex1ActionPerformed(evt);
            }
        });
        jPanel3.add(petSex1);
        petSex1.setBounds(150, 170, 90, 20);
>>>>>>> 47cae230d9c98be4f28adda223dd639c4f2bc686

        jTabbedPane4.addTab("tab1", jPanel3);

        getContentPane().add(jTabbedPane4);
        jTabbedPane4.setBounds(320, 100, 380, 290);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void petStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petStatusActionPerformed

    private void petSex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petSex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petSex1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPetButton;
    private javax.swing.JButton addPetTab;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JTextField emailResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField nameResult;
    private javax.swing.JTextField petAge1;
    private javax.swing.JTextField petBreed1;
    private javax.swing.JTextField petName2;
    private javax.swing.JButton petPhotoUploadButton;
    private javax.swing.JComboBox<String> petSex1;
    private javax.swing.JComboBox<String> petStatus;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton viewPetTab;
    // End of variables declaration//GEN-END:variables
    
    public void addMyRequestButtonListener(ActionListener listener) {
    addPetTab.addActionListener(listener);
    }
    
    public void addSearchButtonListener(ActionListener listener) {
    searchButton.addActionListener(listener);
}
    // For controller to get input from the view
public String getSearchInput() {
    return searchField.getText();
}

// For controller to update search result
public void setSearchResult(String name, String email) {
    nameResult.setText(name);
    emailResult.setText(email);
}

// To clear previous result if user not found
public void clearSearchResult() {
    nameResult.setText("");
    emailResult.setText("");
}
public void addSignOutButtonListener(ActionListener listener){
        signOutButton.addActionListener(listener);
    } 

public void addPetButtonListener(ActionListener listener) {
    addPetButton.addActionListener(listener);
}
public void addPetPhotoUploadButtonListener(ActionListener listener) {
    petPhotoUploadButton.addActionListener(listener);
}

    /**
     * @return the petAge1
     */
    public javax.swing.JTextField getPetAge() {
        return petAge1;
    }

    /**
     * @return the petBreed1
     */
    public javax.swing.JTextField getPetBreed() {
        return petBreed1;
    }

    /**
     * @return the petName2
     */
    public javax.swing.JTextField getPetName() {
        return petName2;
    }

    /**
     * @return the petSex
     */
    public JComboBox<String> getPetSex() {
        return petStatus;
    }
    public String getSelectedPetSex() {
        return (String) petStatus.getSelectedItem();
    }

    /**
     * @return the petStatus
     */
    public JComboBox<String> getPetStatus() {
        return petStatus;
    }
    
    public void addPetTabButtonListener(ActionListener listener) {
    addPetTab.addActionListener(listener);
    }
    
    public void viewPetTabButtonListener(ActionListener listener) {
    viewPetTab.addActionListener(listener);
    }
    
    public javax.swing.JTabbedPane getTabbedPane(){
        return jTabbedPane4;
    }
    
    public String getSelectedPetStatus() {
        return (String) petStatus.getSelectedItem(); // Get the selected item as a String
    }



}
