/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package petadoptiontracker.view;

/**
 *
 * @author keshab
 */
public class EditPetDialog extends java.awt.Dialog {

    /**
     * Creates new form EditPetDialog
     */
    public EditPetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petNameLabel = new javax.swing.JLabel();
        petName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        petNameLabel.setText("jLabel1");
        add(petNameLabel);
        petNameLabel.setBounds(50, 70, 42, 17);

        petName.setText("jTextField1");
        add(petName);
        petName.setBounds(150, 70, 78, 23);

        jLabel2.setText("jLabel1");
        add(jLabel2);
        jLabel2.setBounds(50, 70, 42, 17);

        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(50, 110, 42, 17);

        jTextField2.setText("jTextField2");
        add(jTextField2);
        jTextField2.setBounds(150, 110, 78, 23);

        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(50, 160, 42, 17);

        jTextField3.setText("jTextField3");
        add(jTextField3);
        jTextField3.setBounds(150, 160, 78, 23);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(50, 200, 42, 17);

        jTextField4.setText("jTextField4");
        add(jTextField4);
        jTextField4.setBounds(140, 200, 78, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditPetDialog dialog = new EditPetDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField petName;
    private javax.swing.JLabel petNameLabel;
    // End of variables declaration//GEN-END:variables
}
