/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package petadoptiontracker.view;

/**
 *
 * @author LeathLOQ
 */
public class ForgotPasswordView extends javax.swing.JPanel {

    /**
     * Creates new form ForgotPasswordView
     */
    public ForgotPasswordView() {
        initComponents();
    }
    public static void main(String[] args){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotText = new javax.swing.JLabel();
        EmailEntry = new javax.swing.JTextField();
        CodeEntry = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 255));
        setPreferredSize(new java.awt.Dimension(350, 400));

        ForgotText.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        ForgotText.setForeground(new java.awt.Color(255, 255, 255));
        ForgotText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotText.setText("Forgot Password?");

        EmailEntry.setText("Enter your email");
        EmailEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailEntryActionPerformed(evt);
            }
        });

        CodeEntry.setText("Enter the code");
        CodeEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeEntryActionPerformed(evt);
            }
        });

        ContinueButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ContinueButton.setForeground(new java.awt.Color(0, 51, 255));
        ContinueButton.setText("Continue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmailEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(CodeEntry)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(ForgotText)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(ForgotText)
                .addGap(40, 40, 40)
                .addComponent(EmailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(CodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmailEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailEntryActionPerformed

    private void CodeEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeEntryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeEntry;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JTextField EmailEntry;
    private javax.swing.JLabel ForgotText;
    // End of variables declaration//GEN-END:variables
}
