/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package petadoptiontracker.view;


import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author LeathLOQ
 */
public class ForgotPasswordView extends javax.swing.JPanel {

    /**
     * Creates new form ForgotPasswordView
     */
    public ForgotPasswordView() {
    initComponents();
    }

     public static void main(String[] args) {
        // Use SwingUtilities.invokeLater for thread safety
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Create the JFrame
                JFrame frame = new JFrame("Forgot Password");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                // Add the ForgotPasswordView JPanel to the JFrame
                frame.add(new ForgotPasswordView());
                
                // Set the size of the JFrame
                frame.setSize(350, 400); 
                
                // Make the frame visible
                frame.setVisible(true);
            }
        });
    }

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotText = new javax.swing.JLabel();
        EmailEntry = new javax.swing.JTextField();
        CodeEntry = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();
        ContinueButton1 = new javax.swing.JButton();
        CodeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 78, 201));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setLayout(null);

        ForgotText.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        ForgotText.setForeground(new java.awt.Color(255, 255, 255));
        ForgotText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotText.setText("Forgot Password?");
        add(ForgotText);
        ForgotText.setBounds(110, 30, 220, 28);

        EmailEntry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailEntryActionPerformed(evt);
            }
        });
        add(EmailEntry);
        EmailEntry.setBounds(140, 90, 254, 39);

        CodeEntry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CodeEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeEntryActionPerformed(evt);
            }
        });
        add(CodeEntry);
        CodeEntry.setBounds(140, 230, 254, 41);

        ContinueButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ContinueButton.setForeground(new java.awt.Color(0, 51, 255));
        ContinueButton.setText("Send");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        add(ContinueButton);
        ContinueButton.setBounds(150, 160, 131, 35);

        ContinueButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ContinueButton1.setForeground(new java.awt.Color(0, 51, 255));
        ContinueButton1.setText("Continue");
        add(ContinueButton1);
        ContinueButton1.setBounds(150, 300, 131, 35);

        CodeLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        CodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        CodeLabel.setText("Code:");
        add(CodeLabel);
        CodeLabel.setBounds(50, 230, 80, 35);

        EmailLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email:");
        add(EmailLabel);
        EmailLabel.setBounds(50, 90, 90, 35);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailEntryActionPerformed

    private void CodeEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeEntryActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinueButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeEntry;
    private javax.swing.JLabel CodeLabel;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JButton ContinueButton1;
    private javax.swing.JTextField EmailEntry;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel ForgotText;
    // End of variables declaration//GEN-END:variables
}
