/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package petadoptiontracker.view;


import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author LeathLOQ
 */
public class ForgotPasswordView extends javax.swing.JPanel {

    /**
     * Creates new form ForgotPasswordView
     */
    public ForgotPasswordView() {
    initComponents();
    }

     public static void main(String[] args) {
        // Use SwingUtilities.invokeLater for thread safety
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Create the JFrame
                JFrame frame = new JFrame("Forgot Password");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                // Add the ForgotPasswordView JPanel to the JFrame
                frame.add(new ForgotPasswordView());
                
                // Set the size of the JFrame
                frame.setSize(350, 400); 
                
                // Make the frame visible
                frame.setVisible(true);
            }
        });
    }

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotText = new javax.swing.JLabel();
        EmailEntry = new javax.swing.JTextField();
        CodeEntry = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 255));
        setPreferredSize(new java.awt.Dimension(350, 400));

        ForgotText.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        ForgotText.setForeground(new java.awt.Color(255, 255, 255));
        ForgotText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotText.setText("Forgot Password?");

        EmailEntry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailEntry.setText("Enter your Email");
        EmailEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailEntryActionPerformed(evt);
            }
        });

        CodeEntry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CodeEntry.setText("Enter your Code");
        CodeEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeEntryActionPerformed(evt);
            }
        });

        ContinueButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ContinueButton.setForeground(new java.awt.Color(0, 51, 255));
        ContinueButton.setText("Continue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(ForgotText)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(ForgotText)
                .addGap(33, 33, 33)
                .addComponent(EmailEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(CodeEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmailEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailEntryActionPerformed

    private void CodeEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeEntryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeEntry;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JTextField EmailEntry;
    private javax.swing.JLabel ForgotText;
    // End of variables declaration//GEN-END:variables
}
