/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petadoptiontracker.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author keshab
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forgotPasswordlabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        showPasswordButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 535));
        getContentPane().setLayout(null);
        getContentPane().add(passwordField);
        passwordField.setBounds(310, 170, 240, 30);

        loginButton.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        loginButton.setText("LOGIN");
        getContentPane().add(loginButton);
        loginButton.setBounds(310, 240, 240, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("________________________");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 330, 170, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("OR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 330, 37, 25);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("_________________________");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 330, 210, 30);

        forgotPasswordlabel.setForeground(new java.awt.Color(255, 255, 255));
        forgotPasswordlabel.setText("Forgot password?");
        getContentPane().add(forgotPasswordlabel);
        forgotPasswordlabel.setBounds(380, 290, 140, 20);

        registerLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        registerLabel.setText("SIGN UP");
        getContentPane().add(registerLabel);
        registerLabel.setBounds(310, 380, 240, 30);
        getContentPane().add(emailTextField);
        emailTextField.setBounds(310, 120, 240, 30);

        showPasswordButton.setText("show");
        getContentPane().add(showPasswordButton);
        showPasswordButton.setBounds(580, 170, 72, 23);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 130, 50, 20);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 180, 80, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/loginbg.jpg"))); // NOI18N
        jLabel7.setText(" ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 950, 535);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel forgotPasswordlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerLabel;
    private javax.swing.JButton showPasswordButton;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTextField getEmailTextField(){
        return emailTextField;
    }
     public javax.swing.JPasswordField getPasswordField(){
        return passwordField;
    }
    public void addRegisterListener(MouseListener listener){
        registerLabel.addMouseListener(listener);

    }
    public void addLoginUserListener(ActionListener listener){
        loginButton.addActionListener(listener);
    }
    public void togglePasswordField(boolean visible) {
        passwordField.setEchoChar(visible ? (char) 0 : '*');
        showPasswordButton.setText(visible ? "Hide" : "Show");
    }
    public void showPasswordButtonListener(ActionListener listener){
        showPasswordButton.addActionListener(listener);
    }
    public void forgotPassword(MouseListener listener){
        forgotPasswordlabel.addMouseListener(listener);
    }
}
