/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petadoptiontracker.view;

import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import java.util.Map;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import petadoptiontracker.dao.RequestDao;

/**
 *
 * @author LeathLOQ
 */
public final class NotificationView extends javax.swing.JFrame {
    private final RequestDao requestDao;
    /**
     * Creates new form NotificationView
     */
    public NotificationView() {
        initComponents();
        requestDao=new RequestDao();
        List<Map<String, Object>> requestList = requestDao.getAllRequestsWithUserAndPet();
        updateRequestLabels(requestList);
    }
   // This method will dynamically create labels based on the fetched adoption requests
    public void updateRequestLabels(List<Map<String, Object>> requestList) {
    requestContentPanel.removeAll();  // Clear previous labels

    if (requestList.isEmpty()) {
        JLabel noDataLabel = new JLabel("No adoption requests found.");
        noDataLabel.setFont(new Font("Arial", Font.ITALIC, 14));
        requestContentPanel.add(noDataLabel);
    } else {
        for (Map<String, Object> request : requestList) {
            String userName = (String) request.getOrDefault("user_name", "User");
            String petName = (String) request.getOrDefault("pet_name", "Pet");
            String petBreed = (String) request.getOrDefault("pet_breed", "Breed");
            String status = (String) request.getOrDefault("status", "Pending");
            
            String message = String.format("%s has requested a %s of breed %s. Status: %s \n", userName, petName, petBreed, status);
            JLabel requestLabel = new JLabel(message);
            requestLabel.setFont(new Font("Arial", Font.PLAIN, 14));
            requestLabel.setAlignmentX(LEFT_ALIGNMENT);
            requestLabel.setPreferredSize(new Dimension(400, 30));

            requestContentPanel.add(requestLabel);
            requestContentPanel.add(Box.createVerticalStrut(10));
        }
    }

    // Refresh the panel
    requestContentPanel.revalidate();
    requestContentPanel.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRequestContainer = new javax.swing.JScrollPane();
        requestContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        requestContentPanel.setLayout(new javax.swing.BoxLayout(requestContentPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jPanelRequestContainer.setViewportView(requestContentPanel);

        getContentPane().add(jPanelRequestContainer);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotificationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jPanelRequestContainer;
    private javax.swing.JPanel requestContentPanel;
    // End of variables declaration//GEN-END:variables
}
