/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petadoptiontracker.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import petadoptiontracker.model.PetModel;

/**
 *
 * @author keshab
 */
public class PetProfileView extends javax.swing.JFrame {

    /**
     * Creates new form PetProfileView
     */
    public PetProfileView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        breedLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        photoLabel2 = new javax.swing.JLabel();
        photoLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 480));
        getContentPane().setLayout(null);

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nameLabel.setText("Type");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(40, 140, 160, 20);

        breedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        breedLabel.setText("Breed");
        getContentPane().add(breedLabel);
        breedLabel.setBounds(40, 190, 170, 20);

        ageLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        ageLabel.setText("Age");
        getContentPane().add(ageLabel);
        ageLabel.setBounds(40, 240, 180, 20);

        sexLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        sexLabel.setText("Sex");
        getContentPane().add(sexLabel);
        sexLabel.setBounds(40, 280, 180, 30);

        statusLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        statusLabel.setText("Status");
        getContentPane().add(statusLabel);
        statusLabel.setBounds(40, 330, 200, 30);

        photoLabel.setText("Photo");
        getContentPane().add(photoLabel);
        photoLabel.setBounds(290, 110, 100, 120);

        photoLabel2.setText("Photo");
        getContentPane().add(photoLabel2);
        photoLabel2.setBounds(420, 110, 100, 120);

        photoLabel3.setText("Photo");
        getContentPane().add(photoLabel3);
        photoLabel3.setBounds(550, 110, 100, 120);

        jLabel1.setFont(new java.awt.Font("Satisfy", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Pet Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 30, 220, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/paw.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetProfileView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel breedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel photoLabel2;
    private javax.swing.JLabel photoLabel3;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
    // Constructor to display a specific pet
    public PetProfileView(PetModel pet) {
        initComponents();
        displayPet(pet);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    
    private void displayPet(PetModel pet) {
        nameLabel.setText("Type: " + pet.getName());
        breedLabel.setText("Breed: " + pet.getBreed());
        ageLabel.setText("Age: " + pet.getAge());
        sexLabel.setText("Sex: " + pet.getSex());
        statusLabel.setText("Status: " + pet.getStatus());
        setPhoto(photoLabel, pet.getPhoto());
        setPhoto(photoLabel2, pet.getPhoto2());
        setPhoto(photoLabel3, pet.getPhoto3());
    }
    private void setPhoto(javax.swing.JLabel label, byte[] imageBytes) {
    if (imageBytes != null) {
        ImageIcon icon = new ImageIcon(imageBytes);
        Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
        label.setText("");
    } else {
        label.setIcon(null);
        label.setText("No Photo");
    }
}
}
