package petadoptiontracker.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author keshab
 */
public class RegistrationView extends javax.swing.JFrame {
    File selectedFile;

    /**
     * Creates new form LoginView
     */
    public RegistrationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        noAccountLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        showPasswordButton = new javax.swing.JButton();
        showPasswordButton1 = new javax.swing.JButton();
        uploadImageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 535));
        setSize(new java.awt.Dimension(950, 535));
        getContentPane().setLayout(null);

        jLabel1.setText("Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 70, 80, 17);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 78, 201));
        jLabel2.setText("Enter you details to Register");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 110, 260, 20);
        getContentPane().add(nameTextField);
        nameTextField.setBounds(580, 160, 240, 23);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 160, 34, 17);
        getContentPane().add(emailTextField);
        emailTextField.setBounds(580, 200, 240, 23);

        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 200, 32, 17);

        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 240, 58, 17);
        getContentPane().add(passwordField);
        passwordField.setBounds(580, 240, 240, 23);

        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 280, 110, 20);
        getContentPane().add(confirmPasswordField);
        confirmPasswordField.setBounds(580, 280, 240, 23);

        registerButton.setBackground(new java.awt.Color(38, 78, 201));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Create Account");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(580, 340, 240, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/CreateAccount.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -170, 420, 780);

        noAccountLabel.setText("Already have an account?");
        getContentPane().add(noAccountLabel);
        noAccountLabel.setBounds(580, 400, 160, 20);

        loginLabel.setForeground(new java.awt.Color(38, 78, 201));
        loginLabel.setText("Login");
        getContentPane().add(loginLabel);
        loginLabel.setBounds(740, 400, 42, 20);

        showPasswordButton.setText("Show");
        getContentPane().add(showPasswordButton);
        showPasswordButton.setBounds(830, 240, 72, 23);

        showPasswordButton1.setText("Show");
        getContentPane().add(showPasswordButton1);
        showPasswordButton1.setBounds(830, 280, 72, 23);

        uploadImageButton.setText("Upload Image");
        getContentPane().add(uploadImageButton);
        uploadImageButton.setBounds(630, 310, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel noAccountLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton showPasswordButton;
    private javax.swing.JButton showPasswordButton1;
    private javax.swing.JButton uploadImageButton;
    // End of variables declaration//GEN-END:variables
public void addRegisterUserListener(ActionListener listener) {
        registerButton.addActionListener(listener);
    }
    public void togglePasswordField(boolean visible) {
        passwordField.setEchoChar(visible ? (char) 0 : '*');
        showPasswordButton.setText(visible ? "Hide" : "Show");
    }

    public void toggleConfirmPasswordField(boolean visible) {
        confirmPasswordField.setEchoChar(visible ? (char) 0 : '*');
        showPasswordButton1.setText(visible ? "Hide" : "Show");
    }

    public void addLoginListener(MouseListener listener){
        loginLabel.addMouseListener(listener);
    }
    
    public void showPasswordButtonListener(ActionListener listener){
        showPasswordButton.addActionListener(listener);
    }
    
    public void showPasswordButton1Listener(ActionListener listener){
        showPasswordButton1.addActionListener(listener);
    }
    public void uploadImageButtonListener(ActionListener listener){
        uploadImageButton.addActionListener(listener);
    }

    public void setSelectedFile(File file) {
        this.selectedFile = file;
    }
    
    public javax.swing.JTextField getNameTextField(){
        return nameTextField;
    }
    
    public javax.swing.JTextField getEmailTextField(){
        return emailTextField;
    }
    
    public javax.swing.JPasswordField getPasswordField(){
            return passwordField;
    }
    
    public javax.swing.JPasswordField getConfirmPasswordField(){
        return confirmPasswordField;
    }
    
    public File getSelectedFile(){
        return selectedFile;
    }
}
